name: build

on:
  push:
    #- branches: [master]
    #- tags:
  pull_request:

jobs:
  jvm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: ./gradlew test

  android:
    runs-on: macos-latest

    strategy:
      fail-fast: false

      matrix:
        api-level:
          - 21
          - 24
          - 26
          - 29

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck
        env:
          API_LEVEL: ${{ matrix.api-level }}

